import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/shared/header/Header";
import Footer from "@/components/shared/Footer";


export const metadata: Metadata = {
  title: "Reserved",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="py-3 px-16 flex flex-col min-h-screen"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
